version: '3.9'

services:
    app:
        container_name: app
        image: app
        restart: always
        ports:
            - '${DOCKERPORT}:${PORT}'
        build:
            context: .
            dockerfile: Dockerfile
            target: base
